# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: [/kaggle/input/createyolodataset/fold_2/images/,
        /kaggle/input/createyolodataset/fold_3/images/,
        /kaggle/input/createyolodataset/fold_4/images/,
        /kaggle/input/createyolodataset/fold_5/images/]
val: /kaggle/input/createyolodataset/fold_1/images/

# number of classes
nc: 14

# class names
names: ['Aortic enlargement',
        'Atelectasis',
        'Calcification',
        'Cardiomegaly',
        'Consolidation',
        'ILD',
        'Infiltration',
        'Lung Opacity',
        'Nodule/Mass',
        'Other lesion',
        'Pleural effusion',
        'Pleural thickening',
        'Pneumothorax',
        'Pulmonary fibrosis']